# Generated by Django 3.2.4 on 2021-06-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0002_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
